apiVersion: v2
appVersion: "1.0"
description: Divorce - Fees and Payment Service
name: div-fps
version: 3.0.3
dependencies:
  - name: java
    version: ~3.4.5
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
