java:
    environment:
        FEE_API_URL : "http://fees-register-api-aat.service.core-compute-aat.internal"
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}