java:
    applicationPort: 4009
    ingressHost: "div-fps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    autoscaling:
      enabled: true
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
    environment:
        FEE_API_URL: "http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        FEATURE_FEE_PAY_KEYWORDS: "true"
    aadIdentityName: divorce
    keyVaults:
      div:
        secrets:
          - name: AppInsightsInstrumentationKey
            alias: azure.application-insights.instrumentation-key
