apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  REFORM_ENVIRONMENT : "aat"
  FEE_API_URL : "http://fees-register-api-aat.service.core-compute-aat.internal/fees-register/fees/lookup"
  APPLICATION_INSIGHTS_IKEY : "79656785-5397-4573-93be-ddd7062d5ac3"
  SLOT : "PRODUCTION"
  REFORM_SERVICE_NAME : "fps"
  REFORM_TEAM : "div"
  APPINSIGHTS_INSTRUMENTATIONKEY : "79656785-5397-4573-93be-ddd7062d5ac3"
